name: Build wheels

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheel on Python ${{ matrix.python-version }} / CUDA ${{ matrix.cuda-version }}
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.11"
            cuda-version: "13.0.2"
            torch-cuda-index: "cu130"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          prune-cache: true
          cache-dependency-glob: |
            pyproject.toml
            .github/workflows/build_wheels.yml
          cache-suffix: py${{ matrix.python-version }}-cu${{ matrix.cuda-version }}-${{ matrix.torch-cuda-index }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CUDA Toolkit ${{ matrix.cuda-version }}
        uses: Jimver/cuda-toolkit@v0.2.35
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda-version }}
          method: network
          sub-packages: '["nvcc", "cudart-dev", "cccl", "libcusparse-dev", "libcublas-dev", "libcurand-dev", "libcufft-dev"]'
          log-file-suffix: py${{ matrix.python-version }}-cu${{ matrix.cuda-version }}.txt

      - name: Install build frontend
        run: |
          uv pip install --system "build>=1.5"

      - name: Build wheel
        env:
          CUDA_HOME: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}
          CUDA_PATH: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}
          BUILD_CUDA_EXT: "1"
          TORCH_CUDA_ARCH_LIST: "7.5"

          PIP_INDEX_URL: "https://pypi.org/simple"
          PIP_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/${{ matrix.torch-cuda-index }}"
        run: |
          nvcc -V

          python -m build --wheel

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: bigvgan-wheels-py${{ matrix.python-version }}-cu${{ matrix.cuda-version }}-sm75
          path: dist/*.whl
